#!/bin/sh

#root@IP
server = ""

#All the users
1 = ""
2 = ""
3 = ""
4 = ""
5 = ""
6 = ""

#Password for users
A = ""
B = ""
C = ""
D = ""
E = ""
F = ""



ssh "$server" "mkdir /etc/apt/sources.list.d/"
scp "sources.list" "$server:/etc/apt/"
ssh "$server" "wget --no-check-certificate https://www.dotdeb.org/dotdeb.gpg && apt-key add dotdeb.gpg"
ssh "$server" "wget http://www.deb-multimedia.org/pool/main/d/deb-multimedia-keyring/deb-multimedia-keyring_2016.8.1_all.deb"
ssh "$server" "dpkg -i deb-multimedia-keyring_2016.8.1_all.deb"
scp "dotdeb.list" "$server:/etc/apt/sources.list.d/dotdeb.list"
scp "deb-multimedia.list" "$server:/etc/apt/sources.list.d/deb-multimedia.list"
ssh "$server" "apt-get update"
ssh "$server" "apt-get install automake libcppunit-dev libtool build-essential pkg-config libssl-dev libcurl4-openssl-dev libsigc++-2.0-dev libncurses5-dev screen subversion apache2-utils curl php7.0 php7.0-fpm php7.0-cli php7.0-curl php7.0-geoip git unzip unrar rar zip ffmpeg buildtorrent mediainfo zlib1g-dev"

ssh "$server" "cd /tmp && svn checkout http://svn.code.sf.net/p/xmlrpc-c/code/stable xmlrpc-c && cd xmlrpc-c/ && ./configure && make -j $(nproc) && make install"
ssh "$server" "cd /tmp && git clone https://github.com/rakshasa/libtorrent.git && cd libtorrent && git checkout `git tag | tail -1`"
scp "openssl.patch" "$server:/tmp/libtorrent/openssl.patch"
ssh "$server" "cd /tmp/libtorrent/ && ./autogen.sh && ./configure && make -j $(nproc) && make install"
ssh "$server" "cd /tmp && git clone https://github.com/rakshasa/rtorrent.git && cd rtorrent && git checkout `git tag | tail -1` && ./autogen.sh && ./configure --with-xmlrpc-c && make -j $(nproc) && make install && ldconfig"

ssh "$server" "mkdir -p /var/www/html && cd /var/www/html && git clone https://github.com/Novik/ruTorrent.git rutorrent"
ssh "$server" "cd /var/www/html/rutorrent/plugins/ && git clone https://github.com/xombiemp/rutorrentMobile.git mobile && chown -R www-data:www-data /var/www/html/rutorrent"
scp "conf.php" "$server:/var/www/html/rutorrent/plugins/create/conf.php"
scp "php.ini" "$server:/etc/php/7.0/fpm/php.ini"
ssh "$server" "service php7.0-fpm restart"

ssh "$server" "wget http://nginx.org/keys/nginx_signing.key && apt-key add nginx_signing.key && rm nginx_signing.key"
scp "nginx-mainline.list" "$server:/etc/apt/sources.list.d/nginx-mainline.list"
ssh "$server" "apt-get update && apt-get install nginx && cd /etc/nginx && mkdir auth && rm nginx.conf"
scp "nginx.conf" "$server:/etc/nginx/nginx.conf"
ssh "$server" "cd /etc/nginx && rm conf.d/* && mkdir sites-enabled && mkdir ssl"
scp "seedbox" "$server:/etc/nginx/sites-enables/seedbox"
ssh "$server" "cd /etc/nginx/ssl && openssl ecparam -genkey -name secp384r1 -out seedbox.key &&  openssl req -new -key seedbox.key -sha256 -out seedbox.csr && openssl req -x509 -days 3650 -sha256 -key seedbox.key -in seedbox.csr -out seedbox.crt"
ssh "$server" "chmod 644 /etc/nginx/ssl/*.crt && chmod 640 /etc/nginx/ssl/*.key"
ssh "$server" "useradd --shell /bin/bash --create-home $1 && echo \"$1:$A\" && chpasswd"
ssh "$server" "useradd --shell /bin/bash --create-home $2 && echo \"$2:$B\" && chpasswd"
ssh "$server" "useradd --shell /bin/bash --create-home $3 && echo \"$3:$C\" && chpasswd"
ssh "$server" "useradd --shell /bin/bash --create-home $4 && echo \"$4:$D\" && chpasswd"
ssh "$server" "useradd --shell /bin/bash --create-home $5 && echo \"$5:$E\" && chpasswd"
ssh "$server" "useradd --shell /bin/bash --create-home $6 && echo \"$6:$F\" && chpasswd"
scp "/$1/.rtorrent.rc" "$server:/home/$1/.rtorrent.rc"
scp "/$2/.rtorrent.rc" "$server:/home/$2/.rtorrent.rc"
scp "/$3/.rtorrent.rc" "$server:/home/$3/.rtorrent.rc"
scp "/$4/.rtorrent.rc" "$server:/home/$4/.rtorrent.rc"
scp "/$5/.rtorrent.rc" "$server:/home/$5/.rtorrent.rc"
scp "/$6/.rtorrent.rc" "$server:/home/$6/.rtorrent.rc"
ssh "$server" "mkdir /home/$1/{torrents,perso,.session,watch} && chown --recursive $1:$1 /home/$1"
ssh "$server" "mkdir /home/$2/{torrents,perso,.session,watch} && chown --recursive $2:$2 /home/$2"
ssh "$server" "mkdir /home/$3/{torrents,perso,.session,watch} && chown --recursive $3:$3 /home/$3"
ssh "$server" "mkdir /home/$4/{torrents,perso,.session,watch} && chown --recursive $4:$4 /home/$4"
ssh "$server" "mkdir /home/$5/{torrents,perso,.session,watch} && chown --recursive $5:$5 /home/$5"
ssh "$server" "mkdir /home/$6/{torrents,perso,.session,watch} && chown --recursive $6:$6 /home/$6"
ssh "$server" "chown root:root /home/{$1,$2,$3,$4,$5,$6} && chmod 755 /home/{$1,$2,$3,$4,$5,$6}"
ssh "$server" "echo \"$A\" && htpasswd -i -c /etc/nginx/auth/seedbox_auth $1 && mkdir /var/www/html/rutorrent/conf/users/$1"
ssh "$server" "echo \"$B\" && htpasswd -i /etc/nginx/auth/seedbox_auth $2 && mkdir /var/www/html/rutorrent/conf/users/$2"
ssh "$server" "echo \"$C\" && htpasswd -i /etc/nginx/auth/seedbox_auth $3 && mkdir /var/www/html/rutorrent/conf/users/$3"
ssh "$server" "echo \"$D\" && htpasswd -i /etc/nginx/auth/seedbox_auth $4 && mkdir /var/www/html/rutorrent/conf/users/$4"
ssh "$server" "echo \"$E\" && htpasswd -i /etc/nginx/auth/seedbox_auth $5 && mkdir /var/www/html/rutorrent/conf/users/$5"
ssh "$server" "echo \"$F\" && htpasswd -i /etc/nginx/auth/seedbox_auth $6 && mkdir /var/www/html/rutorrent/conf/users/$6"
ssh "$server" "chmod 777 /etc/nginx/auth/seedbox_auth && chown www-data:www-data /etc/nginx/auth/*"
scp "/$1/config.php" "$server:/var/www/html/rutorrent/conf/users/$1/config.php"
scp "/$2/config.php" "$server:/var/www/html/rutorrent/conf/users/$2/config.php"
scp "/$3/config.php" "$server:/var/www/html/rutorrent/conf/users/$3/config.php"
scp "/$4/config.php" "$server:/var/www/html/rutorrent/conf/users/$4/config.php"
scp "/$5/config.php" "$server:/var/www/html/rutorrent/conf/users/$5/config.php"
scp "/$6/config.php" "$server:/var/www/html/rutorrent/conf/users/$6/config.php"
ssh "$server" "chown -R www-data:www-data /var/www/html && service nginx restart"

scp "/$1/$1-rtorrent" "$server:/etc/init.d/$1-rtorrent"
scp "/$2/$2-rtorrent" "$server:/etc/init.d/$2-rtorrent"
scp "/$3/$3-rtorrent" "$server:/etc/init.d/$3-rtorrent"
scp "/$4/$4-rtorrent" "$server:/etc/init.d/$4-rtorrent"
scp "/$5/$5-rtorrent" "$server:/etc/init.d/$5-rtorrent"
scp "/$6/$6-rtorrent" "$server:/etc/init.d/$6-rtorrent"
ssh "$server" "update-rc.d $1-rtorrent defaults && update-rc.d $2-rtorrent defaults && update-rc.d $3-rtorrent defaults && update-rc.d $4-rtorrent defaults && update-rc.d $5-rtorrent defaults && update-rc.d $6-rtorrent defaults"
ssh "$server" "service $1-rtorrent start && service $2-rtorrent start && service $3-rtorrent start && service $4-rtorrent start && service $5-rtorrent start && service $6-rtorrent start"


scp "plexmediaserver.list" "$server:/etc/apt/sources.list.d/plexmediaserver.list"
ssh "$server" "curl https://downloads.plex.tv/plex-keys/PlexSign.key | apt-key add - && apt-get update && apt-get install plexmediaserver && service plexmediaserver restart"
